apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: expense-tracker
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http