apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: expense-tracker
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: expense-tracker
      app.kubernetes.io/component: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: expense-tracker
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: expense-tracker
      app.kubernetes.io/component: backend
