apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: expense-tracker
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: expense-tracker
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: expense-tracker
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: expense-tracker
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 