apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/component: frontend
data:
  env.js: |
    window.env = {
      REACT_APP_API_URL: "{{ $.Values.ingress.host }}"
    }
