apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-frontend
  labels:
    app.kubernetes.io/name: {{ $.Release.Name }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ $.Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Release.Name }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ $.Values.frontend.image.repository }}:{{ $.Values.frontend.image.tag }}"
          imagePullPolicy: {{ $.Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml $.Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js
      volumes:
        - name: config
          configMap:
            name: {{ $.Release.Name }}-frontend