ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: expense-tracker.example.com
  tls:
    enabled: true
    secretName: expense-tracker-tls

frontend:
  image:
    repository: cbeneke/expense-tracker-frontend
    tag: latest
    pullPolicy: IfNotPresent
    platforms:
      - linux/amd64
      - linux/arm64
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

backend:
  image:
    repository: cbeneke/expense-tracker-backend
    tag: latest
    pullPolicy: IfNotPresent
    platforms:
      - linux/amd64
      - linux/arm64
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

postgresql:
  enabled: true # Set to false to use an external database

  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
    platforms:
      - linux/amd64
      - linux/arm64
  
  # Database configuration
  database: expense_tracker
  username: postgres
  password: postgres

  # External database configuration (used when postgresql.enabled is false)
  external:
    host: ""
    port: 5432
    
  # Resource configuration for postgres
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
      
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""