name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - .github/workflows/ci.yaml
              - .github/workflows/cd.yaml
              - 'backend/**'
            frontend:
              - .github/workflows/ci.yaml
              - .github/workflows/cd.yaml
              - 'frontend/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: backend/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
            version: v1.60

      - name: Run backend tests
        working-directory: backend
        run: go test ./... -v

  build-backend:
    needs: [changes, backend]
    if: |
      always() &&
      needs.changes.outputs.backend == 'true' &&
      (needs.backend.result == 'success' || needs.backend.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          platforms: linux/amd64,linux/arm64
          tags: expense-tracker-backend:pr
          cache-from: type=gha
          cache-to: type=gha,mode=max

  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend linter
        working-directory: frontend
        run: npm run lint
  
  build-frontend:
    needs: [changes, frontend]
    if: |
      always() &&
      needs.changes.outputs.frontend == 'true' &&
      (needs.frontend.result == 'success' || needs.frontend.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          platforms: linux/amd64,linux/arm64
          tags: expense-tracker-frontend:pr
          cache-from: type=gha
          cache-to: type=gha,mode=max
        